### ISSUE TITLE
Invalid narrative in JSON example 20221119/81365677998_815333046_3.json

### ISSUE THREAD

**Issue by aduchate** [hl7-be/hl7-be-fhir-laboratory-report#49]
At line 192 we find : 

```
"text":{
               "status":"generated",
               "div":"<div xmlns=\"http://www.w3.org/1999/xhtml\"><p><b>code: </b>HEMATOLOGIE</p><p><b>subject: </b>Patient/6388178</p><p><b>effective: </b>2021-11-19T00:00:00+01:00</p><p><b>performer: </b>Practitioner/Responsible</p><p><b>member: </b> // Observation/Observation.1.0.0.1 // Observation/Observation.1.0.0.2 // Observation/Observation.1.0.0.3 // Observation/Observation.1.0.0.4 // Observation/Observation.1.0.0.5 // Observation/Observation.1.0.0.6 // Observation/Observation.1.0.0.7 // Observation/Observation"
            }
```

The div should be valid XHTML. Otherwise, the FHIR parser chokes and we are unable to generate a preview.

**Comment by aduchate** [comment]
As a quick fix for this example, I could set the narrative to a sensible value. But it is nevertheless important that you can fix the issue at the source.

**Comment by LotteAd** [comment]
Issue was fixed, thank you!
I will upload the fixed file in the github.

**Comment by aduchate** [comment]
Problem is still present in latest commit. Search for `</b> // Observation/Observation.1.0.0.1` to find the offending narrative.

**Comment by LotteAd** [comment]
Also in the file 81365677998_815333046_5.json? This is the updated version. I managed to see it on the visualisator.

**Comment by aduchate** [comment]
@LotteAd I believe you did not fix the https://github.com/hl7-be/hl7-be-fhir-laboratory-report/blob/master/testing/Macsys/20221119/81365677998_815333046_3.json file but the ones in 20211124.

Could you either fix the other one or get rid of the obsolete directory ?

**Comment by aduchate** [comment]
To be precise the problem is still there: https://github.com/hl7-be/hl7-be-fhir-laboratory-report/blob/e506892f6c41aa39fb5e5ee782772a2459d8c6ee/testing/Macsys/20221119/81365677998_815333046_3.json#L194

**Comment by LotteAd** [comment]
Yes, done! My apologies for the confusion.
